[package]
name = "crossbeam-hamt"
version = "0.1.0"
authors = ["Brandon Allard <ballard2626@gmail.com>", "Tim Ryan <id@timryan.org>"]
publish = false

[lib]
name = "hamt"
path = "src/lib.rs"

[dependencies]
rand = "0.3"
stable-borrow-state = "0.1"
